// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.3
// source: online-control.proto

package control

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Decision int32

const (
	Decision_OK Decision = 0
	Decision_NO Decision = 1
)

// Enum value maps for Decision.
var (
	Decision_name = map[int32]string{
		0: "OK",
		1: "NO",
	}
	Decision_value = map[string]int32{
		"OK": 0,
		"NO": 1,
	}
)

func (x Decision) Enum() *Decision {
	p := new(Decision)
	*p = x
	return p
}

func (x Decision) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Decision) Descriptor() protoreflect.EnumDescriptor {
	return file_online_control_proto_enumTypes[0].Descriptor()
}

func (Decision) Type() protoreflect.EnumType {
	return &file_online_control_proto_enumTypes[0]
}

func (x Decision) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Decision.Descriptor instead.
func (Decision) EnumDescriptor() ([]byte, []int) {
	return file_online_control_proto_rawDescGZIP(), []int{0}
}

type CheckSBPRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// id операции
	OperationId string `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	// uuid ФЛ
	ClientId string `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// сумма перевода в копейках
	Amount int64 `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	// телефон отправителя, пример +79271020000
	SenderPhone string `protobuf:"bytes,4,opt,name=sender_phone,json=senderPhone,proto3" json:"sender_phone,omitempty"`
	// телефон получателя, пример +79271020000
	ReceiverPhone string `protobuf:"bytes,5,opt,name=receiver_phone,json=receiverPhone,proto3" json:"receiver_phone,omitempty"`
	// БИК банка получателя
	ReceiverBic *string `protobuf:"bytes,6,opt,name=receiver_bic,json=receiverBic,proto3,oneof" json:"receiver_bic,omitempty"`
	// ФИО Получателя -  Наименование Получателя
	ReceiverName *string `protobuf:"bytes,7,opt,name=receiver_name,json=receiverName,proto3,oneof" json:"receiver_name,omitempty"`
}

func (x *CheckSBPRequest) Reset() {
	*x = CheckSBPRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_online_control_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckSBPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckSBPRequest) ProtoMessage() {}

func (x *CheckSBPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_online_control_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckSBPRequest.ProtoReflect.Descriptor instead.
func (*CheckSBPRequest) Descriptor() ([]byte, []int) {
	return file_online_control_proto_rawDescGZIP(), []int{0}
}

func (x *CheckSBPRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *CheckSBPRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *CheckSBPRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CheckSBPRequest) GetSenderPhone() string {
	if x != nil {
		return x.SenderPhone
	}
	return ""
}

func (x *CheckSBPRequest) GetReceiverPhone() string {
	if x != nil {
		return x.ReceiverPhone
	}
	return ""
}

func (x *CheckSBPRequest) GetReceiverBic() string {
	if x != nil && x.ReceiverBic != nil {
		return *x.ReceiverBic
	}
	return ""
}

func (x *CheckSBPRequest) GetReceiverName() string {
	if x != nil && x.ReceiverName != nil {
		return *x.ReceiverName
	}
	return ""
}

type CheckSBPResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// решение
	Decision Decision `protobuf:"varint,1,opt,name=decision,proto3,enum=control.Decision" json:"decision,omitempty"`
	// причина отклонения
	DeclineReason *string `protobuf:"bytes,2,opt,name=decline_reason,json=declineReason,proto3,oneof" json:"decline_reason,omitempty"`
}

func (x *CheckSBPResponse) Reset() {
	*x = CheckSBPResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_online_control_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckSBPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckSBPResponse) ProtoMessage() {}

func (x *CheckSBPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_online_control_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckSBPResponse.ProtoReflect.Descriptor instead.
func (*CheckSBPResponse) Descriptor() ([]byte, []int) {
	return file_online_control_proto_rawDescGZIP(), []int{1}
}

func (x *CheckSBPResponse) GetDecision() Decision {
	if x != nil {
		return x.Decision
	}
	return Decision_OK
}

func (x *CheckSBPResponse) GetDeclineReason() string {
	if x != nil && x.DeclineReason != nil {
		return *x.DeclineReason
	}
	return ""
}

var File_online_control_proto protoreflect.FileDescriptor

var file_online_control_proto_rawDesc = []byte{
	0x0a, 0x14, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x2d, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x22,
	0xa8, 0x02, 0x0a, 0x0f, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x53, 0x42, 0x50, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x73,
	0x65, 0x6e, 0x64, 0x65, 0x72, 0x5f, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x25,
	0x0a, 0x0e, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x5f, 0x70, 0x68, 0x6f, 0x6e, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72,
	0x50, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x26, 0x0a, 0x0c, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65,
	0x72, 0x5f, 0x62, 0x69, 0x63, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0b, 0x72,
	0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x42, 0x69, 0x63, 0x88, 0x01, 0x01, 0x12, 0x28, 0x0a,
	0x0d, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x0c, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72,
	0x4e, 0x61, 0x6d, 0x65, 0x88, 0x01, 0x01, 0x42, 0x0f, 0x0a, 0x0d, 0x5f, 0x72, 0x65, 0x63, 0x65,
	0x69, 0x76, 0x65, 0x72, 0x5f, 0x62, 0x69, 0x63, 0x42, 0x10, 0x0a, 0x0e, 0x5f, 0x72, 0x65, 0x63,
	0x65, 0x69, 0x76, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x80, 0x01, 0x0a, 0x10, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x53, 0x42, 0x50, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x2d, 0x0a, 0x08, 0x64, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x11, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x44, 0x65, 0x63, 0x69,
	0x73, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x64, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x2a,
	0x0a, 0x0e, 0x64, 0x65, 0x63, 0x6c, 0x69, 0x6e, 0x65, 0x5f, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0d, 0x64, 0x65, 0x63, 0x6c, 0x69, 0x6e,
	0x65, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x88, 0x01, 0x01, 0x42, 0x11, 0x0a, 0x0f, 0x5f, 0x64,
	0x65, 0x63, 0x6c, 0x69, 0x6e, 0x65, 0x5f, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x2a, 0x1a, 0x0a,
	0x08, 0x44, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10,
	0x00, 0x12, 0x06, 0x0a, 0x02, 0x4e, 0x4f, 0x10, 0x01, 0x32, 0x52, 0x0a, 0x0d, 0x4f, 0x6e, 0x6c,
	0x69, 0x6e, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x12, 0x41, 0x0a, 0x08, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x53, 0x42, 0x50, 0x12, 0x18, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c,
	0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x53, 0x42, 0x50, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x19, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b,
	0x53, 0x42, 0x50, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x19, 0x5a,
	0x17, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c,
	0x3b, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_online_control_proto_rawDescOnce sync.Once
	file_online_control_proto_rawDescData = file_online_control_proto_rawDesc
)

func file_online_control_proto_rawDescGZIP() []byte {
	file_online_control_proto_rawDescOnce.Do(func() {
		file_online_control_proto_rawDescData = protoimpl.X.CompressGZIP(file_online_control_proto_rawDescData)
	})
	return file_online_control_proto_rawDescData
}

var file_online_control_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_online_control_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_online_control_proto_goTypes = []any{
	(Decision)(0),            // 0: control.Decision
	(*CheckSBPRequest)(nil),  // 1: control.CheckSBPRequest
	(*CheckSBPResponse)(nil), // 2: control.CheckSBPResponse
}
var file_online_control_proto_depIdxs = []int32{
	0, // 0: control.CheckSBPResponse.decision:type_name -> control.Decision
	1, // 1: control.OnlineControl.CheckSBP:input_type -> control.CheckSBPRequest
	2, // 2: control.OnlineControl.CheckSBP:output_type -> control.CheckSBPResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_online_control_proto_init() }
func file_online_control_proto_init() {
	if File_online_control_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_online_control_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*CheckSBPRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_online_control_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*CheckSBPResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_online_control_proto_msgTypes[0].OneofWrappers = []any{}
	file_online_control_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_online_control_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_online_control_proto_goTypes,
		DependencyIndexes: file_online_control_proto_depIdxs,
		EnumInfos:         file_online_control_proto_enumTypes,
		MessageInfos:      file_online_control_proto_msgTypes,
	}.Build()
	File_online_control_proto = out.File
	file_online_control_proto_rawDesc = nil
	file_online_control_proto_goTypes = nil
	file_online_control_proto_depIdxs = nil
}
