// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: online-control.proto

package control

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OnlineControl_CheckSBP_FullMethodName = "/control.OnlineControl/CheckSBP"
)

// OnlineControlClient is the client API for OnlineControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OnlineControlClient interface {
	CheckSBP(ctx context.Context, in *CheckSBPRequest, opts ...grpc.CallOption) (*CheckSBPResponse, error)
}

type onlineControlClient struct {
	cc grpc.ClientConnInterface
}

func NewOnlineControlClient(cc grpc.ClientConnInterface) OnlineControlClient {
	return &onlineControlClient{cc}
}

func (c *onlineControlClient) CheckSBP(ctx context.Context, in *CheckSBPRequest, opts ...grpc.CallOption) (*CheckSBPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckSBPResponse)
	err := c.cc.Invoke(ctx, OnlineControl_CheckSBP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OnlineControlServer is the server API for OnlineControl service.
// All implementations must embed UnimplementedOnlineControlServer
// for forward compatibility.
type OnlineControlServer interface {
	CheckSBP(context.Context, *CheckSBPRequest) (*CheckSBPResponse, error)
	mustEmbedUnimplementedOnlineControlServer()
}

// UnimplementedOnlineControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOnlineControlServer struct{}

func (UnimplementedOnlineControlServer) CheckSBP(context.Context, *CheckSBPRequest) (*CheckSBPResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckSBP not implemented")
}
func (UnimplementedOnlineControlServer) mustEmbedUnimplementedOnlineControlServer() {}
func (UnimplementedOnlineControlServer) testEmbeddedByValue()                       {}

// UnsafeOnlineControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OnlineControlServer will
// result in compilation errors.
type UnsafeOnlineControlServer interface {
	mustEmbedUnimplementedOnlineControlServer()
}

func RegisterOnlineControlServer(s grpc.ServiceRegistrar, srv OnlineControlServer) {
	// If the following call pancis, it indicates UnimplementedOnlineControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OnlineControl_ServiceDesc, srv)
}

func _OnlineControl_CheckSBP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckSBPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnlineControlServer).CheckSBP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OnlineControl_CheckSBP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnlineControlServer).CheckSBP(ctx, req.(*CheckSBPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OnlineControl_ServiceDesc is the grpc.ServiceDesc for OnlineControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OnlineControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "control.OnlineControl",
	HandlerType: (*OnlineControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckSBP",
			Handler:    _OnlineControl_CheckSBP_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "online-control.proto",
}
